export const QUERY_KEYS = {
    GET_POSTS: 'GET_ALL_POSTS',
    GET_TOP_CREATORS: 'GET_TOP_CREATORS',
    GET_POST_BY_ID: 'GET_POST_BY_ID',
    GET_RECENT_POSTS: 'GET_RECENT_POSTS',
    GET_CURRENT_USER: 'GET_CURRENT_USER',
    GET_INFINITE_EXPLORE: 'GET_INFINITE_EXPLORE',
    GET_ALL_USERS: 'GET_ALL_USERS',
    GET_USER_BY_ID: 'GET_USER_BY_ID',
}
